version: '3.1'
services:

  db:
    image: mysql:latest
    container_name: mysql
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ../dbdata:/var/lib/mysql
      - ./init/1_sakila.sql:/docker-entrypoint-initdb.d/1_sakila.sql
      - ./init/2_sakila.sql:/docker-entrypoint-initdb.d/2_sakila.sql
    ports: 
       - "4406:3306"

  metabase:
    image: metabase/metabase
    container_name: metabase
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}
      MB_DB_FILE: ${MB_DB_FILE}
      MB_JETTY_PORT: ${MB_JETTY_PORT}
    depends_on:
      - db
    volumes:
      - ../metabase-data:/metabase-data
volumes:
  dbdata:
  metabase-data: