version: '3'
services:

  mysql_db:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    ports: 
       - "4406:3306"    
    env_file:
      - .env
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_USER_PASSWORD: user
      MYSQL_DATABASE: sakila
    volumes:
      - ../dbdata:/var/lib/mysql
      - ./init/1_sakila.sql:/docker-entrypoint-initdb.d/1_sakila.sql
      - ./init/2_sakila.sql:/docker-entrypoint-initdb.d/2_sakila.sql

volumes:
  dbdata: